# Generated by Django 5.0.1 on 2024-01-03 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('description_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.IntegerField(default=0, max_length=10)),
                ('product_number', models.IntegerField(default=0, max_length=10)),
            ],
            options={
                'db_table': 'description',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('image_key', models.IntegerField(default=0, max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('product_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.IntegerField(default=0, max_length=10)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_description', to='products.description')),
                ('productproduct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_description', to='products.product')),
            ],
            options={
                'db_table': 'product_description',
            },
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('product_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(default=0, max_length=10)),
                ('productproduct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_user', to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to='authApp.userprofile')),
            ],
            options={
                'db_table': 'product_user',
            },
        ),
    ]
